### ISSUE TITLE
typing install

### ISSUE THREAD

**Issue by yug95** [rajan-g/angular2-bootstrap-pagination#6]
D:\MyWork\angularApp>postinstall
'postinstall' is not recognized as an internal or external command,
operable program or batch file.

D:\MyWork\angularApp>npm install angular2-bootstrap-pagination --save

> angular2-bootstrap-pagination@2.1.2 postinstall D:\MyWork\angularApp\node_modules\angular2-bootstrap-pagination
> typings install

'typings' is not recognized as an internal or external command,
operable program or batch file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN @angular/animations@4.1.3 requires a peer of @angular/core@4.1.3 but none was installed.
npm WARN angular2-cookie@1.2.6 requires a peer of @angular/common@^2.0.0 but none was installed.
npm WARN angular2-cookie@1.2.6 requires a peer of @angular/core@^2.0.0 but none was installed.
npm WARN angularfire2@4.0.0-rc.0 requires a peer of firebase@^3.6.6 but none was installed.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "angular2-bootstrap-pagination" "--save"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE

npm ERR! angular2-bootstrap-pagination@2.1.2 postinstall: `typings install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-bootstrap-pagination@2.1.2 postinstall script 'typings install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-bootstrap-pagination package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-bootstrap-pagination
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-bootstrap-pagination
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\MyWork\angularApp\npm-debug.log

**Comment by Robouste** [comment]
same here

**Comment by anoop44** [comment]
@Robouste @yug95 You have to install Typings first. Try `npm install typings -g`

**Comment by rajan-g** [comment]
Now I have move to devdependency  area. and fixed you issue
